---
spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  datasource:
    url: jdbc:sqlserver://DbServer01;databaseName=FoodChain
    username: jon
    password: elmer
server:
  port: 9090

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

